// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZu2N4-bJ1rgpdpROuCupmJAkJEGMZ5YQ',
    appId: '1:720830286158:web:b29d34585b79081d7bf61f',
    messagingSenderId: '720830286158',
    projectId: 'e-ticaret-116d8',
    authDomain: 'e-ticaret-116d8.firebaseapp.com',
    storageBucket: 'e-ticaret-116d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN9Dq5zIwVQBoQ6PB1jmc4ZCnvKDvODCo',
    appId: '1:720830286158:ios:365743a295d9b7b37bf61f',
    messagingSenderId: '720830286158',
    projectId: 'e-ticaret-116d8',
    storageBucket: 'e-ticaret-116d8.firebasestorage.app',
    iosBundleId: 'com.ahmet.firebaseeticaret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN9Dq5zIwVQBoQ6PB1jmc4ZCnvKDvODCo',
    appId: '1:720830286158:ios:365743a295d9b7b37bf61f',
    messagingSenderId: '720830286158',
    projectId: 'e-ticaret-116d8',
    storageBucket: 'e-ticaret-116d8.firebasestorage.app',
    iosBundleId: 'com.ahmet.firebaseeticaret',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZu2N4-bJ1rgpdpROuCupmJAkJEGMZ5YQ',
    appId: '1:720830286158:web:fe93ca2d6534dcdd7bf61f',
    messagingSenderId: '720830286158',
    projectId: 'e-ticaret-116d8',
    authDomain: 'e-ticaret-116d8.firebaseapp.com',
    storageBucket: 'e-ticaret-116d8.firebasestorage.app',
  );
}
